core/e621_code/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'

  Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  mount Sidekiq::Web => '/sidekiq', constraints: AdminRouteConstraint.new

  namespace :admin do
    resources :users, :only => [:edit, :update, :edit_blacklist, :update_blacklist, :alt_list] do
      member do
        get :edit_blacklist
        post :update_blacklist
        get :request_password_reset
        post :password_reset
      end
      collection do
        get :alt_list
      end
    end
    resource :alias_and_implication_import, :only => [:new, :create]
    resource :dashboard, :only => [:show]
    resources :exceptions, only: [:index, :show]
  end
  resources :edit_histories
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :search
      end
    end
    resources :invitations, :only => [:new, :create, :index]
    resource :tag, :only => [:edit, :update]
    namespace :post do
      resource :queue, :only => [:show] do
        member do
          get :random
        end
      end
      resource :approval, :only => [:create, :destroy]
      resources :disapprovals, :only => [:create, :index]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
        end
      end
    end
    resources :invitations, :only => [:new, :create, :index, :show]
    resources :ip_addrs, :only => [:index, :search] do
      collection do
        get :search
      end
    end
  end
  namespace :explore do
    resources :posts, :only => [] do
      collection do
        get :popular
        get :searches
        get :missed_searches
        get :intro
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
      resource :api_key, :only => [:show, :view, :update, :destroy] do
        post :view
      end
    end
  end

  resources :tickets do
    member do
      post :claim
      post :unclaim
    end
  end

  resources :takedowns do
    collection do
      post :count_matching_posts
    end
    member do
      post :add_by_ids
      post :add_by_tags
      post :remove_by_ids
    end
  end

  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
    end
    collection do
      get :show_or_new
      get :banned
    end
  end
  resources :artist_urls, only: [:index, :update]
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resource :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
    end
    member do
      post :hide
      post :unhide
    end
  end
  resources :comment_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :delayed_jobs, :only => [:index, :destroy] do
    member do
      put :run
      put :retry
      put :cancel
    end
  end
  resources :dmails, :only => [:new, :create, :index, :show, :destroy] do
    member do
      post :spam
      post :ham
    end
    collection do
      post :mark_all_as_read
    end
  end
  resource :dtext_preview, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :forum_posts do
    resource :votes, controller: "forum_post_votes"
    member do
      post :hide
      post :unhide
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :hide
      post :unhide
      get :new_merge
      post :create_merge
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :forum_categories
  resources :help_pages, controller: "help", path: "help"
  resources :ip_bans
  resources :upload_whitelists do
    collection do
      get :is_allowed
    end
  end
  resources :email_blacklists
  resource :iqdb_queries, :only => [:show] do
    collection do
      post :show
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :janitor_trials do
    collection do
      get :test
    end
    member do
      put :promote
      put :demote
    end
  end
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
      post :undelete
      get :import
      get :import_preview
      post :import_posts
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create, :destroy] do
    collection do
      get :all_select
    end
  end
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
  end
  resources :post_replacements, :only => [:index, :new, :create, :update]
  resources :deleted_posts, only: [:index]
  resources :posts, :only => [:index, :show, :update] do
    resources :events, :only => [:index], :controller => "post_events"
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :votes, :controller => "post_votes", :only => [:create, :destroy]
    resource :flag, controller: 'post_flags', only: [:destroy]
    collection do
      get :random
    end
    member do
      get :update_iqdb
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
      get :comments, to: "comments#for_post"
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :post_appeals
  resources :post_flags, except: [:destroy]
  resources :post_approvals, only: [:index]
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries, :only => [:index, :show] do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resource :related_tag, :only => [:show, :update]
  match "related_tag/bulk", to: "related_tags#bulk", via: [:get, :post]
  resource :recommended_posts, only: [:show]
  resource :session, only: [:new, :create, :destroy] do
    get :sign_out, on: :collection
  end
  resource :source, :only => [:show]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
      post :preview
    end
  end
  resources :tag_type_versions
  resources :tag_aliases do
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :uploads
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"
    resource :api_key, :only => [:show, :view, :update, :destroy], :controller => "maintenance/user/api_keys" do
      post :view
    end

    collection do
      get :home
      get :search
      get :upload_limit
      get :custom_style
    end
  end
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests do
    member do
      post :approve
      post :reject
    end
  end
  resource :user_revert, :only => [:new, :create]
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resources :blips do
    member do
      post :hide
      post :unhide
    end
  end
  resources :post_report_reasons
  resources :post_sets do
    collection do
      get :atom
      get :for_select
    end
    member do
      get :maintainers
      get :post_list
      post :update_posts
      post :add_posts
      post :remove_posts
    end
  end
  resources :post_set_maintainers do
    member do
      get :approve
      get :block
      get :deny
    end
  end
  resource :email do
    collection do
      get :activate_user
      get :resend_confirmation
    end
  end

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")

core/e621_code/app/controllers/related_tags_controller.rb
class RelatedTagsController < ApplicationController
  respond_to :json, :html, only: [:show]
  respond_to :json, only: [:bulk]
  before_action :member_only

  def show
    @query = RelatedTagQuery.new(query: params[:query], category: params[:category], user: CurrentUser.user)
    expires_in 30.second
    respond_with(@query)
  end

  def bulk
    @query = BulkRelatedTagQuery.new(query: params[:query], category: params[:category], user: CurrentUser.user)
    respond_with(@query) do |fmt|
      fmt.json do
        render json: @query.to_json
      end
    end
  end
end

core/e621_code/app/views/related_tags/_buttons.html.erb
<%= button_tag "Related tags", type: :button, class: "related-tags-button ui-button ui-widget ui-corner-all sub" %>

<% TagCategory.related_button_list.each do |category| %>
  <%= button_tag TagCategory.related_button_mapping[category], type: :button, "data-category": category, class: "related-tags-button ui-button ui-widget ui-corner-all sub" %>
<% end %>

core/e621_code/app/views/related_tags/_container.html.erb
<div id="related-tags-container" class="visible">
  <h3>
    Related Tags
    <a href="#" id="show-related-tags-link">»</a>
    <a href="#" id="hide-related-tags-link">«</a>
  </h3>

  <div class="related-tags">
    <%= render "related_tags/user_tags", related_tags: nil %>
    <%= render "related_tags/current_tags", related_tags: nil %>
    <%= render "related_tags/source_tags", source: nil %>
  </div>
</div>

core/e621_code/app/views/related_tags/_current_tags.html.erb
<div class="current-related-tags-columns">
  <% if related_tags.present? %>
    <%= render "related_tags/tag_column", tags: related_tags.tags, class: "general-related-tags-column", title: related_tags.pretty_name %>
    <%= render "related_tags/tag_column", tags: related_tags.wiki_page_tags, class: "wiki-related-tags-column", title: link_to("wiki:#{related_tags.pretty_name}", show_or_new_wiki_pages_path(title: related_tags.query)) %>

    <% related_tags.other_wiki_pages.each do |wiki| %>
      <%= render "related_tags/tag_column", tags: wiki.tags, class: "other-wiki-related-tags-column", title: link_to("wiki:#{wiki.pretty_title}", show_or_new_wiki_pages_path(title: wiki.title)) %>
    <% end %>
  <% end %>
</div>

core/e621_code/app/views/related_tags/_source_tags.html.erb
<div class="source-related-tags-columns">
  <% if source.present? %>
    <%= render "related_tags/tag_column", tags: source.translated_tags.map(&:name), title: "Translated Tags" %>

    <div class="tag-column wide-column artist-related-tags-column">
      <h6>Artist</h6>

      <% if source.artists.size == 0 %>
        none
      <% else %>
        <% if source.artists.any?(&:is_banned?) %>
          <%= TagSetPresenter.new(["avoid_posting"]).tag_list_html(name_only: true) %>
        <% end %>

        <% source.artists.each do |artist| %>
          <%= TagSetPresenter.new([artist.name]).tag_list_html(name_only: true) %>

          <ul>
            <% artist.sorted_urls.each do |url| %>
              <li>
                <% if url.is_active %>
                  <%= external_link_to url.url, truncate: 64, strip_scheme: true, link_options: {target: "_blank"} %>
                  <%= link_to tag.i(class: "fas fa-minus-circle"), artist_url_path(id: url.id, artist_url: { is_active: false }), remote: true, method: :put, "data-confirm": "This will mark the URL as inactive. Continue?" %>
                <% else %>
                  <del><%= external_link_to url.url, truncate: 64, strip_scheme: true, link_options: {target: "_blank"} %></del>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

core/e621_code/app/views/related_tags/_tag_column.html.erb
<%# tags, title, class (optional) %>

<%= content_tag(:div, class: ["tag-column", local_assigns[:class] || "#{title.parameterize}-related-tags-column", "is-empty-#{tags.empty?}"].join(" ")) do %>
  <% if tags.present? %>
    <h6><%= title %></h6>
    <%= TagSetPresenter.new(tags).tag_list_html(name_only: true) %>
  <% end %>
<% end %>

core/e621_code/app/views/related_tags/_user_tags.html.erb
<div class="user-related-tags-columns">
  <% if related_tags.present? %>
    <%= render "related_tags/tag_column", tags: related_tags.recent_tags, title: "Recent" %>
    <%= render "related_tags/tag_column", tags: related_tags.favorite_tags, title: "Frequent" %>
  <% end %>
</div>

core/e621_code/app/views/related_tags/show.html.erb
<div id="c-related-tags">
  <div id="a-show">
    <h1>Related tags</h1>
    <section>
      <%= form_tag(related_tag_path, :method => :get) do %>
        <%= text_field_tag "query", params[:query], :data => { :autocomplete => "tag" } %>
        <%= select_tag "category", options_for_select([""] + TagCategory.canonical_mapping.map{|x| [x.first, x.first.downcase]}, params[:category]) %>
        <%= submit_tag "Show"%>
      <% end %>
    </section>
    <% if params[:query].present? %>
      <section>
        <table class="striped">
          <thead>
            <tr>
              <th>Name</th>
            </tr>
          </thead>
          <tbody>
            <% @query.tags_for_html.each do |tag, category| %>
              <tr>
                <td class="category-<%= category %>">
                  <%= link_to("?", show_or_new_wiki_pages_path(:title => tag)) %>
                  <%= link_to(tag, posts_path(:tags => tag)) %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </section>
     <% end %>
  </div>
</div>

<%= render "tags/secondary_links" %>

<% content_for(:page_title) do %>
  Related tags - <%= Danbooru.config.app_name %>
<% end %>