core/e621_code/config/routes.rb
Rails.application.routes.draw do

  require 'sidekiq/web'
  require 'sidekiq_unique_jobs/web'

  Sidekiq::Web.set :session_secret, Rails.application.credentials[:secret_key_base]
  mount Sidekiq::Web => '/sidekiq', constraints: AdminRouteConstraint.new

  namespace :admin do
    resources :users, :only => [:edit, :update, :edit_blacklist, :update_blacklist, :alt_list] do
      member do
        get :edit_blacklist
        post :update_blacklist
        get :request_password_reset
        post :password_reset
      end
      collection do
        get :alt_list
      end
    end
    resource :alias_and_implication_import, :only => [:new, :create]
    resource :dashboard, :only => [:show]
    resources :exceptions, only: [:index, :show]
  end
  resources :edit_histories
  namespace :moderator do
    resource :dashboard, :only => [:show]
    resources :ip_addrs, :only => [:index] do
      collection do
        get :search
      end
    end
    resources :invitations, :only => [:new, :create, :index]
    resource :tag, :only => [:edit, :update]
    namespace :post do
      resource :queue, :only => [:show] do
        member do
          get :random
        end
      end
      resource :approval, :only => [:create, :destroy]
      resources :disapprovals, :only => [:create, :index]
      resources :posts, :only => [:delete, :undelete, :expunge, :confirm_delete] do
        member do
          get :confirm_delete
          post :expunge
          post :delete
          post :undelete
          get :confirm_move_favorites
          post :move_favorites
          get :confirm_ban
          post :ban
          post :unban
        end
      end
    end
    resources :invitations, :only => [:new, :create, :index, :show]
    resources :ip_addrs, :only => [:index, :search] do
      collection do
        get :search
      end
    end
  end
  namespace :explore do
    resources :posts, :only => [] do
      collection do
        get :popular
        get :searches
        get :missed_searches
        get :intro
      end
    end
  end
  namespace :maintenance do
    namespace :user do
      resource :count_fixes, only: [:new, :create]
      resource :email_notification, :only => [:show, :destroy]
      resource :password_reset, :only => [:new, :create, :edit, :update]
      resource :login_reminder, :only => [:new, :create]
      resource :deletion, :only => [:show, :destroy]
      resource :email_change, :only => [:new, :create]
      resource :dmail_filter, :only => [:edit, :update]
      resource :api_key, :only => [:show, :view, :update, :destroy] do
        post :view
      end
    end
  end

  resources :tickets do
    member do
      post :claim
      post :unclaim
    end
  end

  resources :takedowns do
    collection do
      post :count_matching_posts
    end
    member do
      post :add_by_ids
      post :add_by_tags
      post :remove_by_ids
    end
  end

  resources :artists do
    member do
      put :revert
      put :ban
      put :unban
    end
    collection do
      get :show_or_new
      get :banned
    end
  end
  resources :artist_urls, only: [:index, :update]
  resources :artist_versions, :only => [:index] do
    collection do
      get :search
    end
  end
  resources :bans
  resources :bulk_update_requests do
    member do
      post :approve
    end
  end
  resources :comments do
    resource :votes, :controller => "comment_votes", :only => [:create, :destroy]
    collection do
      get :search
    end
    member do
      post :hide
      post :unhide
    end
  end
  resources :comment_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :delayed_jobs, :only => [:index, :destroy] do
    member do
      put :run
      put :retry
      put :cancel
    end
  end
  resources :dmails, :only => [:new, :create, :index, :show, :destroy] do
    member do
      post :spam
      post :ham
    end
    collection do
      post :mark_all_as_read
    end
  end
  resource :dtext_preview, :only => [:create]
  resources :favorites, :only => [:index, :create, :destroy]
  resources :forum_posts do
    resource :votes, controller: "forum_post_votes"
    member do
      post :hide
      post :unhide
    end
    collection do
      get :search
    end
  end
  resources :forum_topics do
    member do
      post :hide
      post :unhide
      get :new_merge
      post :create_merge
      post :subscribe
      post :unsubscribe
    end
    collection do
      post :mark_all_as_read
    end
    resource :visit, :controller => "forum_topic_visits"
  end
  resources :forum_categories
  resources :help_pages, controller: "help", path: "help"
  resources :ip_bans
  resources :upload_whitelists do
    collection do
      get :is_allowed
    end
  end
  resources :email_blacklists
  resource :iqdb_queries, :only => [:show] do
    collection do
      post :show
      get :preview
      get :check, to: redirect {|path_params, req| "/iqdb_queries?#{req.query_string}"}
    end
  end
  resources :janitor_trials do
    collection do
      get :test
    end
    member do
      put :promote
      put :demote
    end
  end
  resources :mod_actions
  resources :news_updates
  resources :notes do
    collection do
      get :search
    end
    member do
      put :revert
    end
  end
  resources :note_versions, :only => [:index]
  resource :note_previews, :only => [:show]
  resources :pools do
    member do
      put :revert
      post :undelete
      get :import
      get :import_preview
      post :import_posts
    end
    collection do
      get :gallery
    end
    resource :order, :only => [:edit], :controller => "pool_orders"
  end
  resource :pool_element, :only => [:create, :destroy] do
    collection do
      get :all_select
    end
  end
  resources :pool_versions, :only => [:index] do
    member do
      get :diff
    end
  end
  resources :post_replacements, :only => [:index, :new, :create, :update]
  resources :deleted_posts, only: [:index]
  resources :posts, :only => [:index, :show, :update] do
    resources :events, :only => [:index], :controller => "post_events"
    resources :replacements, :only => [:index, :new, :create], :controller => "post_replacements"
    resource :votes, :controller => "post_votes", :only => [:create, :destroy]
    resource :flag, controller: 'post_flags', only: [:destroy]
    collection do
      get :random
    end
    member do
      get :update_iqdb
      put :revert
      put :copy_notes
      get :show_seq
      put :mark_as_translated
      get :comments, to: "comments#for_post"
    end
    get :similar, :to => "iqdb_queries#index"
  end
  resources :post_votes, only: [:index, :delete, :lock] do
    collection do
      post :lock
      post :delete
    end
  end
  resources :post_appeals
  resources :post_flags, except: [:destroy]
  resources :post_approvals, only: [:index]
  resources :post_versions, :only => [:index, :search] do
    member do
      put :undo
    end
    collection do
      get :search
    end
  end
  resources :artist_commentaries, :only => [:index, :show] do
    collection do
      put :create_or_update
      get :search
    end
    member do
      put :revert
    end
  end
  resource :related_tag, :only => [:show, :update]
  match "related_tag/bulk", to: "related_tags#bulk", via: [:get, :post]
  resource :recommended_posts, only: [:show]
  resource :session, only: [:new, :create, :destroy] do
    get :sign_out, on: :collection
  end
  resource :source, :only => [:show]
  resources :tags do
    resource :correction, :only => [:new, :create, :show], :controller => "tag_corrections"
    collection do
      get :autocomplete
      post :preview
    end
  end
  resources :tag_type_versions
  resources :tag_aliases do
    member do
      post :approve
    end
  end
  resource :tag_alias_request, :only => [:new, :create]
  resources :tag_implications do
    member do
      post :approve
    end
  end
  resource :tag_implication_request, :only => [:new, :create]
  resources :uploads
  resources :users do
    resource :password, :only => [:edit], :controller => "maintenance/user/passwords"
    resource :api_key, :only => [:show, :view, :update, :destroy], :controller => "maintenance/user/api_keys" do
      post :view
    end

    collection do
      get :home
      get :search
      get :upload_limit
      get :custom_style
    end
  end
  resources :user_feedbacks do
    collection do
      get :search
    end
  end
  resources :user_name_change_requests do
    member do
      post :approve
      post :reject
    end
  end
  resource :user_revert, :only => [:new, :create]
  resources :wiki_pages do
    member do
      put :revert
    end
    collection do
      get :search
      get :show_or_new
    end
  end
  resources :wiki_page_versions, :only => [:index, :show, :diff] do
    collection do
      get :diff
    end
  end
  resources :blips do
    member do
      post :hide
      post :unhide
    end
  end
  resources :post_report_reasons
  resources :post_sets do
    collection do
      get :atom
      get :for_select
    end
    member do
      get :maintainers
      get :post_list
      post :update_posts
      post :add_posts
      post :remove_posts
    end
  end
  resources :post_set_maintainers do
    member do
      get :approve
      get :block
      get :deny
    end
  end
  resource :email do
    collection do
      get :activate_user
      get :resend_confirmation
    end
  end

  # aliases
  resources :wpages, :controller => "wiki_pages"
  resources :ftopics, :controller => "forum_topics"
  resources :fposts, :controller => "forum_posts"

  # legacy aliases
  get "/artist" => redirect {|params, req| "/artists?page=#{req.params[:page]}&search[name]=#{CGI::escape(req.params[:name].to_s)}"}
  get "/artist/index" => redirect {|params, req| "/artists?page=#{req.params[:page]}"}
  get "/artist/show/:id" => redirect("/artists/%{id}")

core/e621_code/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  respond_to :html
  before_action :member_only, except: [:index]
  before_action :admin_only, only: [:update, :edit, :destroy, :claim, :unclaim]


  def index
    @tickets = Ticket.search(search_params).paginate(params[:page], limit: params[:limit])
    respond_with(@tickets)
  end

  def new
    @ticket = Ticket.new(qtype: params[:type], disp_id: params[:disp_id])
    check_new_permission(@ticket)
  end

  def create
    @ticket = Ticket.create(ticket_params)
    if @ticket.valid?
      flash[:notice] = 'Ticket created'
      redirect_to(ticket_path(@ticket))
    else
      respond_with(@ticket)
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
    check_permission(@ticket)
    respond_with(@ticket)
  end

  def update
    @ticket = Ticket.find(params[:id])
    @ticket.transaction do
      if @ticket.claimant_id.present? && @ticket.claimant_id != CurrentUser.id && params[:force_claim] != 'true'
        flash[:error] = "Ticket has already been claimed by somebody else, submit again to force."
        redirect_to ticket_path(@ticket, force_claim: 'true')
        return
      end
      @ticket.handler_id = CurrentUser.id
      @ticket.claimant_id = CurrentUser.id
      @ticket.update(update_ticket_params)
    end

    respond_with(@ticket)
  end

  def claim
    @ticket = Ticket.find(params[:id])

    if @ticket.claimant.nil?
      @ticket.claim!
      redirect_to ticket_path(@ticket)
      return
    end
    flash[:error] = 'Ticket already claimed.'
    redirect_to ticket_path(@ticket)
  end

  def unclaim
    @ticket = Ticket.find(params[:id])

    if @ticket.claimant.nil?
      flash[:error] = 'Ticket not claimed.'
      redirect_to ticket_path(@ticket)
      return
    elsif @ticket.claimant.id != CurrentUser.id
      flash[:error] = 'Ticket not claimed by you.'
      redirect_to ticket_path(@ticket)
      return
    end
    @ticket.unclaim!
    flash[:notice] = 'Claim removed.'
    redirect_to ticket_path(@ticket)
  end

  private

  def ticket_params
    params.require(:ticket).permit(%i[qtype disp_id reason report_reason])
  end

  def update_ticket_params
    params.require(:ticket).permit(%i[response status])
  end

  def search_params
    search_params = params.fetch(:search, {})
    allowed = %i[type status order]
    allowed += %i[creator_id] if CurrentUser.is_admin? || (search_params[:creator_id].present? && search_params[:creator_id].to_i == CurrentUser.id)
    allowed += %i[creator_name accused_name accused_id claimant_id] if CurrentUser.is_admin?
    search_params.permit(allowed)
  end

  def check_new_permission(ticket)
    unless ticket.can_create_for?(CurrentUser.user)
      raise User::PrivilegeError
    end
  end

  def check_permission(ticket)
    unless ticket.can_see_details?(CurrentUser.user)
      raise User::PrivilegeError
    end
  end

end

core/e621_code/app/helpers/ticket_helper.rb
module TicketHelper
  def pretty_ticket_status(ticket)
    status = ticket.status
    if status == "partial"
      "Under Investigation"
    elsif status == "approved"
      "Investigated"
    else
      status.titleize
    end
  end
end

core/e621_code/app/views/tickets/_footer.html.erb
<% content_for("subnavbar") do %>
  <li><%= link_to "All", action: "index" %></li>
  <% unless current_user.anon? %>
  <li><%= link_to "Mine", action: "index", user_id: current_user.id %></li>
  <% end %>
  <% if current_user.is_admin? %>
    <li><%= link_to "Claimed", action: "index", claim_id: current_user.id %></li>
  <% end %>
  <li><%= link_to "Help", controller: "help" %></li>
<% end %>

core/e621_code/app/views/tickets/_search.html.erb
<div id='searchform_hide'>
  <%= search_show_link %>
</div>
<%= simple_form_for(:search, method: :get, defaults: {required: false}, html: {id: 'searchform', class: "inline-form"}) do |f| %>
  <% if CurrentUser.is_admin? %>
    <%= f.input :creator_name, label: "Reporter", input_html: {value: params[:search][:creator_name]} %>
    <%= f.input :creator_id, label: "Reporter ID", input_html: {value: params[:search][:creator_id]} %>
    <%= f.input :accused_name, label: "Accused", input_html: {value: params[:search][:accused_name]} %>
  <% end %>
  <%= f.input :type, collection: [
      ["Any", ""],
      ["User complaint", "user"],
      ["Private message complaint", "dmail"],
      ["Comment complaint", "comment"],
      ["Forum post complaint", "forum"],
      ["Blip complaint", "blip"],
      ["Wiki complaint", "wiki"],
      ["Username change", "namechange"],
      ["Pool complaint", "pool"],
      ["Set complaint", "set"],
      ["Post complaint", "post"]
  ], selected: params[:search][:type] %>
  <%= f.input :status, collection: [
      ["Any", ""],
      ["Approved/investigated", "approved"],
      ["Under investigation", "partial"],
      ["Pending", "pending"],
      ["Denied", "denied"]
  ], selected: params[:search][:status] %>
  <%= f.submit "Search" %>
  <%= search_hide_link %>
<% end %>

core/e621_code/app/views/tickets/_secondary_links.html.erb
<% content_for(:secondary_links) do %>
  <menu>
    <%= subnav_link_to 'List', tickets_path %>
    <% unless CurrentUser.is_anonymous? %>
      <%= subnav_link_to 'Mine', tickets_path(search: {creator_id: CurrentUser.id}) %>
    <% end %>
    <% if CurrentUser.is_admin? %>
    <%= subnav_link_to 'Claimed', tickets_path(search: {claimant_id: CurrentUser.id}) %>
    <% end %>
  </menu>
<% end %>

core/e621_code/app/views/tickets/index.html.erb
<div id="c-tickets">
  <div id="a-index">

  </div>
</div>

<%= render partial: 'search' %>

<h2>Ticket Center</h2>
<table class="valign striped">
	<thead>
		<tr>
			<th style="width:5%">ID</th>
			<% if CurrentUser.is_admin? %>
			<th style="width:10%">Reporter</th>
      <th style="width:10%">Claimed By</th>
			<% end %>
			<th style="width:15%">Type</th>
			<th style="width:25%">Subject</th>
			<th style="width:8%">Status</th>
			<th style="width:10%">Updated</th>
			<th style="width:18%">Created</th>
		</tr>
	</thead>

	<tbody>
		<% @tickets.each do |ticket| %>
			<tr data-link="<%= ticket_path(ticket) %>">
				<td><%= link_to ticket.id, ticket_path(ticket) %></td>
				<% if CurrentUser.is_admin? %>
				<td>
					<%= link_to_user ticket.creator %>
				</td>
        <td>
          <% if ticket.claimant.nil? %>
            <span class="redtext">Unclaimed</span>
          <% else %>
            <%= link_to_user ticket.claimant %>
          <% end %>
        </td>
				<% end %>
				<td><%= link_to ticket.type_title, ticket_path(ticket) %></td>

				<% if !ticket.can_see_reason?(CurrentUser.user) %>
					<td><span style="cursor:help;" class="redtext" title="Due to privacy concerns, this information is confidential">Confidential</span></td>
				<% else %>
					<td class="ticket-subject" title="<%= h(truncate(strip_dtext(ticket.reason), length: 200)) %>"><%= link_to h(strip_dtext(truncate(ticket.subject, length: 200))), action: "show", id: ticket.id %></td>
				<% end %>

				<td class="<%= ticket.status %>-ticket"><%= pretty_ticket_status(ticket) %></td>
				<td style="cursor:help;" title="<%= ticket.updated_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(ticket.updated_at) %> ago</td>
				<td style="cursor:help;" title="<%= ticket.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(ticket.created_at) %> ago</td>
			</tr>
		<% end %>
	</tbody>
</table>

<div id="paginator">
  <%= numbered_paginator(@tickets) %>
</div>

<% render partial: 'secondary_links' %>

core/e621_code/app/views/tickets/new.html.erb
<div id="c-tickets">
  <div id="a-new">

    <%= simple_form_for(@ticket) do |f| %>
      <% @found_item = true %>
      <% if params[:type].nil? %>
        <% @found_item = false %>
        <div class='section' style='width:80em;'>
          To submit a ticket about a problematic comment, click "Report" on the comment itself.<br/>
          To submit a ticket about a problematic forum post, click "Report" on the post itself.<br/>
          To submit a ticket about a problematic pool, click "Report" on the pool page itself.<br/>
          To submit a ticket about a problematic set, click "Report" on the set page itself.<br/>
          To submit a ticket about a problematic user, click "Report" on the user's profile page.<br/>
          To submit a ticket about a problematic private message, click "Report PM" above the PM itself.<br/>
          To submit a username request, click "Request Username Change" on <a href='/user/home'>the user home page</a>.<br/>
        </div>
      <% elsif CurrentUser.is_anonymous? %>
        <% @found_item = false %>
        <div class='section' style='width:80em;'>
          You must be logged in to submit a ticket. Please <a href='/user/login'>log in</a> and try again.
        </div>
      <% elsif @ticket.type_valid %>
        <%= render partial: "tickets/new_types/#{@ticket.qtype}" %>
      <% else %>
        <% @found_item = false %>
        <div class='section' style='width:80em;'>
          Hmm, it seems you tried to report something that doesn't make sense.
        </div>
      <% end %>

      <% if @found_item %>
        <%= f.hidden_field :disp_id %>
        <%= f.hidden_field :qtype %>

        <div class='section' style='width:80em;'>
          <label for="ticket_reason">
            <% if params[:type] == "namechange" %>
              Desired username
            <% elsif params[:type] == "post" %>
              Additional details.
            <% else %>
              Reason for complaint
            <% end %>
          </label><br/>

          <% if params[:type] == "namechange" %>
            <p class='nomargin'>Note: Multiple name change requests made within a short period of time may not be
              honored</p>
            <%= f.input :reason, as: :text, maxlength: 20 %><br/>
          <% else %>
            <p class='nomargin'>Note: Abuse of this system will lead to disciplinary action</p>
            <%= dtext_field "ticket", "reason", :value => @ticket.reason, :input_id => "ticket_reason", :preview_id => "dtext-preview-for-ticket-reason" %>
          <% end %>

        </div>
        <% if params[:type] == "namechange" %>
          <%= submit_tag "Submit Request" %>
        <% else %>
          <%= submit_tag "Submit Complaint" %> <%= dtext_preview_button "ticket", "reason", :input_id => "ticket_reason", :preview_id => "dtext-preview-for-ticket-reason" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<% render partial: 'secondary_links' %>

core/e621_code/app/views/tickets/show.html.erb
<div id="c-tickets">
  <div id="a-show">
    <div class='section'>
      <h3><%= @ticket.type_title %> Ticket</h3>

      <table>
        <% if @ticket.qtype == "namechange" %>
          <tr>
            <td><span class='title'>Original Name</span></td>
            <td><%= link_to h(@ticket.oldname), controller: "user", action: "show", id: @ticket.user_id %></td>
          </tr>
        <% elsif @ticket.can_see_username?(CurrentUser) %>
          <tr>
            <td><span class='title'>Requested by</span></td>
            <td><%= link_to_user @ticket.creator %></td>
          </tr>
        <% end %>
        <tr>
          <td><span class="title">Created</span></td>
          <td style="cursor:help;" title="<%= @ticket.created_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@ticket.created_at) %> ago</td>
        </tr>
        <tr>
          <td><span class="title">Updated</span></td>
          <td style="cursor:help;" title="<%= @ticket.updated_at.strftime("%b %d, %Y %I:%M %p") %>"><%= time_ago_in_words(@ticket.updated_at) %> ago</td>
        </tr>
        <% if CurrentUser.is_admin? %>
          <tr>
            <td><span class="title">Claimed By</span></td>
            <% if @ticket.claimant.nil? %>
              <td id="claimed_by"><%= link_to 'Claim', claim_ticket_path(@ticket), method: :post %></td>
            <% else %>
              <td id="claimed_by"><%= @ticket.claimant.name %>
                <% if @ticket.claimant.id == CurrentUser.id %> | <%= link_to 'Unclaim', unclaim_ticket_path(@ticket), method: :post %><% end %></td>
            <% end %>
          </tr>
        <% end %>
        <tr>
          <td><span class='title'>Status</span></td>
          <td class="<%= @ticket.status %>-ticket"><%= pretty_ticket_status(@ticket) %></td>
        </tr>

        <% if CurrentUser.is_admin? %>
          <tr>
            <td><span class='title'>IP</span></td>
            <td><%= link_to_ip(@ticket.creator_ip_addr) %></td>
          </tr>
          <tr>
            <td><span class="title">Open Duplicates</span></td>
            <td><ul>
              <% @ticket.open_duplicates.where('id != ?', @ticket.id).find_each do |dup| %>
              <li><%= link_to("Ticket #{dup.id} - #{dup.subject}", ticket_path(dup.id)) %></li>
              <% end %>
            </ul></td>
          </tr>
        <% end %>

        <%= render partial: "tickets/types/#{@ticket.qtype}" %>

        <tr>
          <% if (@ticket.qtype == "namechange") %>
            <td><span class='title'>Desired Name</span></td>
          <% else %>
            <td><span class='title'>Reason</span></td>
          <% end %>

          <% if @ticket.can_see_reason?(CurrentUser) %>
            <td class="styled-dtext"><%= format_text(@ticket.reason) %></td>
          <% else %>
            <td><span style="cursor:help;" class="redtext" title="Due to privacy concerns, this information is confidential">Confidential</span></td>
          <% end %>
        </tr>

        <% if(!@ticket.response.blank?) %>
          <tr>
            <td><span class='title'>Handled by</span></td>
            <% if (!@ticket.handler.nil?)%>
              <td><%= link_to_user @ticket.handler %></td>
            <% else %>
              <td>Unknown</td>
            <% end %>
          </tr>

          <tr>
            <td><span class='title'>Response</span></td>
            <% if @ticket.can_see_response?(CurrentUser) %>
              <td class="styled-dtext"><%= format_text(!@ticket.response.blank? ? @ticket.response : "No response.") %></td>
            <% else %>
              <td><span style="cursor:help;" class="redtext" title="Due to privacy concerns, this information is confidential">Confidential</span></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>

    <% if CurrentUser.is_admin? %>
      <%= simple_form_for(@ticket) do |f| %>
        <div class='section'>
          <% if (@ticket.qtype == "namechange") %>
            <table>
              <tr>
                <% if @ticket.status == "pending" %>
                  <td colspan="2"><input type="checkbox" name="no_username_change" id="no_username_change"/> <label for="no_username_change">Don't automatically change username to <span class='yellowtext'><%= @ticket.reason %></span> (use <%= fast_link_to("this form", controller: "user", action: "change_username", id: @ticket.user_id, newname: @ticket.reason) %>)</label></td>
                <% else %>
                  <td colspan="2">Ticket has already been approved/denied, so no automatic username change will happen.<br /><%= fast_link_to("Username change form", controller: "user", action: "change_username", id: @ticket.user_id, newname: @ticket.reason) %></td>
                <% end %>
              </tr>
              <tr>
                <td><span class='title'>Status</span></td>
                <td>
                  <select name="ticket[status]">
                    <option value="approved">Approved</option>
                    <option value="denied">Denied</option>
                  </select>
                </td>
              </tr>
              <tr>
                <td><span class='title'>Reason</span></td>
                <td><%= text_field "ticket", "response", size: 50, value: "Username changed" %></td>
              </tr>
            </table>
            <%= submit_tag "Submit" %>
          <% else %>
            <table>
              <%= f.input :status, collection: [['Investigated', 'approved'], ['Under Investigation', 'partial']], selected: @ticket.status || 'approved' %>
              <tr>
                <td><%= dtext_field "ticket", "response", input_classes: 'ticket-response', :value => @ticket.response, :input_id => "ticket_response_for_#{@ticket.id}", :preview_id => "dtext-preview-for-#{@ticket.id}" %></td>
              </tr>
            </table>
            <%= tag.input name: 'force_claim', type: 'hidden', value: params[:force_claim] %>
            <%= f.button :submit, "Submit" %>
            <%= dtext_preview_button "ticket", "response", :input_id => "ticket_response_for_#{@ticket.id}", :preview_id => "dtext-preview-for-#{@ticket.id}" %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<% content_for(:title) do %>
  <%= @ticket.type_title %>
<% end %>

<% render partial: 'secondary_links' %>